### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by adenosine-phosphatase** [tenable/ghidra_tools#14]
Hi, 

I get the following error after running the script. 
ENV.Variable initialized with API key, Ghidra restarted, python 3.8.3, Windows 11 ...

Traceback (most recent call last):
  File "C:\Users\XXXX\ghidra_scripts\NewScript.py", line 569, in <module>
    comment = add_explanatory_comment_to_current_function(
  File "C:\Users\XXXX\ghidra_scripts\NewScript.py", line 385, in add_explanatory_comment_to_current_function
    function_name = function.getName()
AttributeError: 'NoneType' object has no attribute 'getName'

**Comment by oblivia-simplex** [comment]
This can happen if you run the script before selecting a function. I'll update it so that it gives you a more meaningful error message. For now, before running the script, try clicking somewhere in the decompiler listing for the function of interest first. This will give the current address and current function variables non-null values.

**Comment by adenosine-phosphatase** [comment]
That helped, thanks. So now the script managed to do most of its job ("This function appears to be performing some cleanup tasks before  terminating.  First, it initializes...") .
The execution does end with another error though:
Traceback (most recent call last):
  File "D:\Downloads\ghidra\ghidra_9.0\Ghidra\Features\Base\ghidra_scripts\g3po.py", line 573, in <module>
    apply_renaming_suggestions(comment)
  File "D:\Downloads\ghidra\ghidra_9.0\Ghidra\Features\Base\ghidra_scripts\g3po.py", line 539, in apply_renaming_suggestions
    old = sanitize_variable_name(old)
  File "D:\Downloads\ghidra\ghidra_9.0\Ghidra\Features\Base\ghidra_scripts\g3po.py", line 509, in sanitize_variable_name
    name = list(filter(lambda x: len(x) > 0, name.split(" ")))[0]
IndexError: index out of range: 0

**Comment by oblivia-simplex** [comment]
Just fixed that bug. Should be working smoothly in the next PR. (coming soon)Sent from my iPhoneOn May 10, 2023, at 4:30 AM, Ivica Stipovic ***@***.***> wrote:﻿
That helped, thanks. So now the script managed to do most of its job ("This function appears to be performing some cleanup tasks before  terminating.  First, it initializes...") .
The execution does end with another error though:
Traceback (most recent call last):
File "D:\Downloads\ghidra\ghidra_9.0\Ghidra\Features\Base\ghidra_scripts\g3po.py", line 573, in 
apply_renaming_suggestions(comment)
File "D:\Downloads\ghidra\ghidra_9.0\Ghidra\Features\Base\ghidra_scripts\g3po.py", line 539, in apply_renaming_suggestions
old = sanitize_variable_name(old)
File "D:\Downloads\ghidra\ghidra_9.0\Ghidra\Features\Base\ghidra_scripts\g3po.py", line 509, in sanitize_variable_name
name = list(filter(lambda x: len(x) > 0, name.split(" ")))[0]
IndexError: index out of range: 0

**Comment by oblivia-simplex** [comment]
alright, the fix has been merged
